# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmMCUPipeline-conn'
    subscriptionId: '93715f7a-35d5-4271-8ec0-197254b8617c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Adastra-MCU-RG'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: 'mcu-examples/azuredeploy.json'
    overrideParameters: '-Name mcustoragegithub -storagePrefix "mcustore" -storageSKU Standard_LRS -webAppName "mcudemoapp"'
    deploymentMode: 'Incremental'
    deploymentName: 'MCUDeploymentTemplate'